### ISSUE TITLE
Add version bounds on liburing

### ISSUE THREAD

**Issue by phadej** [well-typed/blockio-uring#7]
Both lower and upper bounds

It looks like liburing is actively developed library: https://github.com/axboe/liburing/blob/1fdcca14b9af2daea50bf1f08605875ffda349e7/CHANGELOG

Especially having the lower bound on `liburing` is important that this library doesn't use something not present in old `liburing`. Testing with that version is obviously a must (e.g. using an older debian or ubuntu image).

**Comment by dcoutts** [comment]
Yeah, and it should be easy since it uses pkg-config.

**Comment by phadej** [comment]
Note, Ubuntu 22.04 LTS (`jammy`) uses 2.1 https://packages.ubuntu.com/jammy/liburing2

**Comment by dcoutts** [comment]
Fixed by #9.
